### ISSUE TITLE
JOSS REVIEW - Software paper

### ISSUE THREAD

**Issue by cforgaci** [UrbanRuralSystems/ur-scape#10]
The paper is very clear and well written. There is one detail that could be improved. The summary reads like an introduction, not mentioning the proposed solution and high-level functionality. I recommend adding 1-2 sentences at the end of the summary about how ur-scape responds to the stated technological developments and the specific challenge of dealing with large amounts of data in the urbanizing regions of Asia and Africa.  The first paragraph of the Statement of need might do just that. Consider moving it to the Summary.

**Comment by luyuhao0326** [comment]
@cforgaci very good point. We have added a new paragraph in the summary to highlight the key contribution of ur-scape as a software tool. Please let me know if you have any other questions.

**Comment by cforgaci** [comment]
Thank you for improving the summary. I have no other questions here, so I will close this issue.
