### ISSUE TITLE
JOSS REVIEW - Documentation

### ISSUE THREAD

**Issue by cforgaci** [UrbanRuralSystems/ur-scape#11]
I would like to suggest a few improvements to the repository's README file.

I recommend making the description of ur-scape more explicit about the high-level functionality of the software stated in the paper. Consider adding your sentence from the paper

> Supported by Unity game-engine, ur-scape aims to improve stakeholder access to data **[and analysis]** through an innovative data rendering format and an intuitive UI/UX concept. 

after the first sentence in the README and mentioning also the analytical functionality of the tool as suggested in bold.

Some links in the README are broken. Including the full url, with `https://`, in the markdown links should make them work.

Besides the stated contribution guidelines, you could specify when and how should issues/bugs be reported and/or where third parties can seek support.

**Comment by luyuhao0326** [comment]
@cforgaci Thanks for these suggestions on the README file. 

- The suggested text has been moved to the README file. 
- I have included the contact information for collaboration and bug reporting. 
- All the links have now been fixed.

**Comment by cforgaci** [comment]
@luyuhao0326, thank you for making those improvements. Please note that the FCL link still does not work. It could be simply merged with the link to Agropolitan Cities.

**Comment by luyuhao0326** [comment]
@cforgaci I am so sorry. I missed a "/" in the url. Classic mistake. It should work now. Thank you very much for double checking it again.

**Comment by cforgaci** [comment]
@luyuhao0326 thanks for making this tiny correction :). We can close this issue now.
