### ISSUE TITLE
JOSS Review – Software paper

### ISSUE THREAD

**Issue by winstonyym** [UrbanRuralSystems/ur-scape#8]
[#4664 joss-reviews](https://github.com/openjournals/joss-reviews/issues/4664#issue-1334082133)

hi @luyuhao0326, I have some minor comments for the paper. Aside from that, I think the paper is written clearly and has all the key components required by JOSS. 

-URL on line 77 needs to be checked.
-Line 42, 44, and 66 has minor typos.

**Comment by luyuhao0326** [comment]
Thanks a lot @winstonyym for catching these issues. We will look into them and get back to you :)

**Comment by luyuhao0326** [comment]
- line 77: the link is working in markdown. But in JOSS generated PDF preview, there is an additional "-" in the link and it seems to be causing the issue. 
- line 66: changed Bundung to Bandung
- line 44: changed seemless to seamless 
- line 42: changed ultising to utilising

**Comment by winstonyym** [comment]
Great, thanks for fixing these issues. I think this issue can be closed.
